import "@/styles/globals.css";
import MantainRegistry from "@/application/utils/MantainRegistry";
import DashboardLayout from "@/ui/layouts/dashboard/dashboard";
import React, { PropsWithChildren } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <MantainRegistry>
          <DashboardLayout>{children}</DashboardLayout>
        </MantainRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
